name = "theurbanworld"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
main = ".output/server/index.mjs"

[assets]
binding = "ASSETS"
directory = ".output/public"
