name = "theurbanworld"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
main = ".output/server/index.mjs"

[assets]
binding = "ASSETS"
directory = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "theurbanworld-db"
database_id = "64e8c8c4-5619-4c17-8ef6-41dec33dacaf"
